version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: yarn start
    ports:
      - 33324:33324
    volumes:
      - .:/app
