version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - API_DOMAIN=${REACT_APP_API_DOMAIN}
    command: yarn start
    ports:
      - 33324:33324
    volumes:
      - .:/app
